import streamlit as st
import os


def show_explore_page():
    # Add grand title at the top
    st.title("Data Exploration")

    # Define a dictionary with image file names as keys and appropriate titles and descriptions as values
    image_titles = {
        "top_words_cloud.png": ("Top Movie Name Keywords", "This word cloud visualizes the most common keywords in movie titles."),
        "genres_revenue.png": ("Genres vs Revenue", "This graph demonstrates the relationship between movie genres and their revenue."),
        "release_date_graph.png": ("Release Date Distribution", "This chart shows the distribution of movie release dates over time."),
        "revenue_on_month_of_movie_release.png": ("Revenue by Month of Movie Release", "This graph highlights the revenue generated by movies based on their release month."),
        "runtime-vs-revenue.png": ("Runtime vs. Revenue", "This scatter plot illustrates the correlation between a movie's runtime and its revenue."),
        "weekday_release_revenue.png": ("Weekday vs Revenue", "This chart compares movie revenue based on the day of the week a movie is released."),
        "feature_importance.png": ("Feature Importance", "This bar chart demonstrates the importance of various features in predicting movie revenue."),
    }

    # Display the images with appropriate titles and descriptions
    for image_file, (title, description) in image_titles.items():
        st.header(title)
        image_path = os.path.join("assets", image_file)
        st.image(image_path, use_column_width=True)
        st.write(description)
